version: 2
updates:
- package-ecosystem: yarn
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  automerged_updates:
    - match:
        dependency_type: all
        update_type: semver:minor
