name: CI

on:
  push:
    branches-ignore:
      - 'bump-v*'
    tags-ignore:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: test put-with-s3-event-response
        shell: bash
        run: docker-compose -f ./test/docker-compose.yml run put-with-s3-event-response
      - name: test resize-image
        shell: bash
        run: docker-compose -f ./test/docker-compose.yml run resize-image
      - name: test simple-event
        shell: bash
        run: docker-compose -f ./test/docker-compose.yml run simple-event
      - name: test simple-event-python
        shell: bash
        run: docker-compose -f ./test/docker-compose.yml run simple-event-python
      - name: test simple-put
        shell: bash
        run: docker-compose -f ./test/docker-compose.yml run simple-put
      - name: test webpack-support
        shell: bash
        run: docker-compose -f ./test/docker-compose.yml run webpack-support
